-- Pembatalan migrasi nama tampilan mob.
USE `RTK`;

UPDATE `Mobs` SET `MobDescription` = 'Rabbit' WHERE `MobId` = 1;
UPDATE `Mobs` SET `MobDescription` = 'Squirrel' WHERE `MobId` = 2;
UPDATE `Mobs` SET `MobDescription` = 'Deer' WHERE `MobId` = 3;
UPDATE `Mobs` SET `MobDescription` = 'Doe' WHERE `MobId` = 4;
UPDATE `Mobs` SET `MobDescription` = 'Plain monkey' WHERE `MobId` = 5;
UPDATE `Mobs` SET `MobDescription` = 'White Rabbit' WHERE `MobId` = 6;
UPDATE `Mobs` SET `MobDescription` = 'Blue rooster' WHERE `MobId` = 7;
UPDATE `Mobs` SET `MobDescription` = 'Horse' WHERE `MobId` = 8;
UPDATE `Mobs` SET `MobDescription` = 'Wolf' WHERE `MobId` = 9;
UPDATE `Mobs` SET `MobDescription` = 'Rat' WHERE `MobId` = 10;
UPDATE `Mobs` SET `MobDescription` = 'Cat' WHERE `MobId` = 11;
UPDATE `Mobs` SET `MobDescription` = 'Sly monkey' WHERE `MobId` = 12;
UPDATE `Mobs` SET `MobDescription` = 'Spry monkey' WHERE `MobId` = 13;
UPDATE `Mobs` SET `MobDescription` = 'Ugly monkey' WHERE `MobId` = 14;
UPDATE `Mobs` SET `MobDescription` = 'Vile rat' WHERE `MobId` = 16;
UPDATE `Mobs` SET `MobDescription` = 'Blood rat' WHERE `MobId` = 17;
UPDATE `Mobs` SET `MobDescription` = 'Killer rat' WHERE `MobId` = 18;
UPDATE `Mobs` SET `MobDescription` = 'Large bull' WHERE `MobId` = 19;
UPDATE `Mobs` SET `MobDescription` = 'Raging bull' WHERE `MobId` = 20;
UPDATE `Mobs` SET `MobDescription` = 'Charging ox' WHERE `MobId` = 21;
UPDATE `Mobs` SET `MobDescription` = 'Stubborn piglet' WHERE `MobId` = 22;
UPDATE `Mobs` SET `MobDescription` = 'Stubborn pig' WHERE `MobId` = 23;
UPDATE `Mobs` SET `MobDescription` = 'Fat pig' WHERE `MobId` = 24;
UPDATE `Mobs` SET `MobDescription` = 'Stubborn warthog' WHERE `MobId` = 25;
UPDATE `Mobs` SET `MobDescription` = 'Fierce dog' WHERE `MobId` = 26;
UPDATE `Mobs` SET `MobDescription` = 'Fighting dog' WHERE `MobId` = 27;
UPDATE `Mobs` SET `MobDescription` = 'Mad dog' WHERE `MobId` = 28;
UPDATE `Mobs` SET `MobDescription` = 'Pale dog' WHERE `MobId` = 29;
UPDATE `Mobs` SET `MobDescription` = 'Black chick' WHERE `MobId` = 30;
UPDATE `Mobs` SET `MobDescription` = 'Wild chicken' WHERE `MobId` = 31;
UPDATE `Mobs` SET `MobDescription` = 'Wild rooster' WHERE `MobId` = 32;
UPDATE `Mobs` SET `MobDescription` = 'Radiant chick' WHERE `MobId` = 33;
UPDATE `Mobs` SET `MobDescription` = 'Plain snake' WHERE `MobId` = 34;
UPDATE `Mobs` SET `MobDescription` = 'Blood snake' WHERE `MobId` = 35;
UPDATE `Mobs` SET `MobDescription` = 'Radiant snake' WHERE `MobId` = 36;
UPDATE `Mobs` SET `MobDescription` = 'Fire snake' WHERE `MobId` = 37;
UPDATE `Mobs` SET `MobDescription` = 'Wild horse' WHERE `MobId` = 38;
UPDATE `Mobs` SET `MobDescription` = 'Young dragon' WHERE `MobId` = 45;
UPDATE `Mobs` SET `MobDescription` = 'Fierce Sheep' WHERE `MobId` = 46;
UPDATE `Mobs` SET `MobDescription` = 'Ugly Sheep' WHERE `MobId` = 47;
UPDATE `Mobs` SET `MobDescription` = 'Ice Beast' WHERE `MobId` = 48;
UPDATE `Mobs` SET `MobDescription` = 'Mouse' WHERE `MobId` = 49;
UPDATE `Mobs` SET `MobDescription` = 'White rat' WHERE `MobId` = 50;
UPDATE `Mobs` SET `MobDescription` = 'Centipede' WHERE `MobId` = 51;
UPDATE `Mobs` SET `MobDescription` = 'Fierce mouse' WHERE `MobId` = 52;
UPDATE `Mobs` SET `MobDescription` = 'Bat' WHERE `MobId` = 53;
UPDATE `Mobs` SET `MobDescription` = 'Big bat' WHERE `MobId` = 54;
UPDATE `Mobs` SET `MobDescription` = 'Big rat' WHERE `MobId` = 55;
UPDATE `Mobs` SET `MobDescription` = 'Silver squirrel' WHERE `MobId` = 56;
UPDATE `Mobs` SET `MobDescription` = 'Golden rabbit' WHERE `MobId` = 57;
UPDATE `Mobs` SET `MobDescription` = 'Fox' WHERE `MobId` = 70;
UPDATE `Mobs` SET `MobDescription` = 'Sheep' WHERE `MobId` = 71;
UPDATE `Mobs` SET `MobDescription` = 'Snake' WHERE `MobId` = 72;
UPDATE `Mobs` SET `MobDescription` = 'Black buck' WHERE `MobId` = 73;
UPDATE `Mobs` SET `MobDescription` = 'Blood wolf' WHERE `MobId` = 74;
UPDATE `Mobs` SET `MobDescription` = 'Dark fox' WHERE `MobId` = 75;
UPDATE `Mobs` SET `MobDescription` = 'Blood fox' WHERE `MobId` = 76;
UPDATE `Mobs` SET `MobDescription` = 'Lava fox' WHERE `MobId` = 77;
UPDATE `Mobs` SET `MobDescription` = 'Sun fox' WHERE `MobId` = 78;
UPDATE `Mobs` SET `MobDescription` = 'Raven' WHERE `MobId` = 80;
UPDATE `Mobs` SET `MobDescription` = 'Nine-tailed fox' WHERE `MobId` = 81;
UPDATE `Mobs` SET `MobDescription` = 'Nine-tailed fox' WHERE `MobId` = 82;
UPDATE `Mobs` SET `MobDescription` = 'Nine-tailed fox' WHERE `MobId` = 83;
UPDATE `Mobs` SET `MobDescription` = 'Monkey sentry' WHERE `MobId` = 87;
UPDATE `Mobs` SET `MobDescription` = 'Sheep veteran' WHERE `MobId` = 88;
UPDATE `Mobs` SET `MobDescription` = 'Witch' WHERE `MobId` = 91;
UPDATE `Mobs` SET `MobDescription` = 'Witch shaman' WHERE `MobId` = 93;
UPDATE `Mobs` SET `MobDescription` = 'Skeleton mage' WHERE `MobId` = 95;
UPDATE `Mobs` SET `MobDescription` = 'Skeleton warrior' WHERE `MobId` = 96;
UPDATE `Mobs` SET `MobDescription` = 'Giant centipede' WHERE `MobId` = 97;
UPDATE `Mobs` SET `MobDescription` = 'Large centipede' WHERE `MobId` = 98;
UPDATE `Mobs` SET `MobDescription` = 'Giant spider' WHERE `MobId` = 100;
UPDATE `Mobs` SET `MobDescription` = 'Giant scorpion' WHERE `MobId` = 101;
UPDATE `Mobs` SET `MobDescription` = 'Radiant spider' WHERE `MobId` = 103;
UPDATE `Mobs` SET `MobDescription` = 'Pale scorpion' WHERE `MobId` = 104;
UPDATE `Mobs` SET `MobDescription` = 'Sheep sentry' WHERE `MobId` = 106;
UPDATE `Mobs` SET `MobDescription` = 'Wild piglet' WHERE `MobId` = 107;
UPDATE `Mobs` SET `MobDescription` = 'Worm' WHERE `MobId` = 108;
UPDATE `Mobs` SET `MobDescription` = 'Wild pig' WHERE `MobId` = 109;
UPDATE `Mobs` SET `MobDescription` = 'Mud snake' WHERE `MobId` = 110;
UPDATE `Mobs` SET `MobDescription` = 'Fire worm' WHERE `MobId` = 111;
UPDATE `Mobs` SET `MobDescription` = 'Mud bull' WHERE `MobId` = 112;
UPDATE `Mobs` SET `MobDescription` = 'Earth snake' WHERE `MobId` = 113;
UPDATE `Mobs` SET `MobDescription` = 'Warthog' WHERE `MobId` = 114;
UPDATE `Mobs` SET `MobDescription` = 'Hare' WHERE `MobId` = 116;
UPDATE `Mobs` SET `MobDescription` = 'Nine-tailed fox' WHERE `MobId` = 118;
UPDATE `Mobs` SET `MobDescription` = 'Strange thing' WHERE `MobId` = 119;
UPDATE `Mobs` SET `MobDescription` = 'Ox sentry' WHERE `MobId` = 122;
UPDATE `Mobs` SET `MobDescription` = 'Boar sentry' WHERE `MobId` = 123;
UPDATE `Mobs` SET `MobDescription` = 'Boar champion' WHERE `MobId` = 125;
UPDATE `Mobs` SET `MobDescription` = 'Dark wolf' WHERE `MobId` = 127;
UPDATE `Mobs` SET `MobDescription` = 'Large hare' WHERE `MobId` = 128;
UPDATE `Mobs` SET `MobDescription` = 'Red hare' WHERE `MobId` = 130;
UPDATE `Mobs` SET `MobDescription` = 'Giant mantis' WHERE `MobId` = 131;
UPDATE `Mobs` SET `MobDescription` = 'Blood mantis' WHERE `MobId` = 132;
UPDATE `Mobs` SET `MobDescription` = 'Dark buck' WHERE `MobId` = 135;
UPDATE `Mobs` SET `MobDescription` = 'Dark deer' WHERE `MobId` = 136;
UPDATE `Mobs` SET `MobDescription` = 'Horse sentry' WHERE `MobId` = 138;
UPDATE `Mobs` SET `MobDescription` = 'Dog sentry' WHERE `MobId` = 145;
UPDATE `Mobs` SET `MobDescription` = 'Dog assassin' WHERE `MobId` = 147;
UPDATE `Mobs` SET `MobDescription` = 'Rat sentry' WHERE `MobId` = 148;
UPDATE `Mobs` SET `MobDescription` = 'Frost ogre' WHERE `MobId` = 150;
UPDATE `Mobs` SET `MobDescription` = 'Ice ogre' WHERE `MobId` = 152;
UPDATE `Mobs` SET `MobDescription` = 'Dragon sentry' WHERE `MobId` = 161;
UPDATE `Mobs` SET `MobDescription` = 'Dragon mage' WHERE `MobId` = 162;
UPDATE `Mobs` SET `MobDescription` = 'Snake sentry' WHERE `MobId` = 164;
UPDATE `Mobs` SET `MobDescription` = 'White wolf' WHERE `MobId` = 165;
UPDATE `Mobs` SET `MobDescription` = 'Divine mouse' WHERE `MobId` = 166;
UPDATE `Mobs` SET `MobDescription` = 'Mud rat' WHERE `MobId` = 167;
UPDATE `Mobs` SET `MobDescription` = 'Lava rat' WHERE `MobId` = 169;
UPDATE `Mobs` SET `MobDescription` = 'Rat guardian' WHERE `MobId` = 170;
UPDATE `Mobs` SET `MobDescription` = 'Spirit mouse' WHERE `MobId` = 171;
UPDATE `Mobs` SET `MobDescription` = 'Earth rat' WHERE `MobId` = 172;
UPDATE `Mobs` SET `MobDescription` = 'Fire rat' WHERE `MobId` = 173;
UPDATE `Mobs` SET `MobDescription` = 'Rat defender' WHERE `MobId` = 175;
UPDATE `Mobs` SET `MobDescription` = 'Mighty mouse' WHERE `MobId` = 177;
UPDATE `Mobs` SET `MobDescription` = 'Divine rat' WHERE `MobId` = 178;
UPDATE `Mobs` SET `MobDescription` = 'Spirit rat' WHERE `MobId` = 180;
UPDATE `Mobs` SET `MobDescription` = 'Rat avenger' WHERE `MobId` = 181;
UPDATE `Mobs` SET `MobDescription` = 'Green squirrel' WHERE `MobId` = 185;
UPDATE `Mobs` SET `MobDescription` = 'Blue deer' WHERE `MobId` = 186;
UPDATE `Mobs` SET `MobDescription` = 'Blue doe' WHERE `MobId` = 187;
UPDATE `Mobs` SET `MobDescription` = 'Blue rabbit' WHERE `MobId` = 188;
UPDATE `Mobs` SET `MobDescription` = 'Green deer' WHERE `MobId` = 189;
UPDATE `Mobs` SET `MobDescription` = 'Green doe' WHERE `MobId` = 190;
UPDATE `Mobs` SET `MobDescription` = 'Green rabbit' WHERE `MobId` = 191;
UPDATE `Mobs` SET `MobDescription` = 'Orange deer' WHERE `MobId` = 192;
UPDATE `Mobs` SET `MobDescription` = 'Orange doe' WHERE `MobId` = 193;
UPDATE `Mobs` SET `MobDescription` = 'Orange rabbit' WHERE `MobId` = 194;
UPDATE `Mobs` SET `MobDescription` = 'Red deer' WHERE `MobId` = 195;
UPDATE `Mobs` SET `MobDescription` = 'Red doe' WHERE `MobId` = 196;
UPDATE `Mobs` SET `MobDescription` = 'Red rabbit' WHERE `MobId` = 197;
UPDATE `Mobs` SET `MobDescription` = 'Blind mouse' WHERE `MobId` = 198;
UPDATE `Mobs` SET `MobDescription` = 'Blind rat' WHERE `MobId` = 199;
UPDATE `Mobs` SET `MobDescription` = 'Blind centipede' WHERE `MobId` = 201;
UPDATE `Mobs` SET `MobDescription` = 'Blind mantis' WHERE `MobId` = 203;
UPDATE `Mobs` SET `MobDescription` = 'Dark tiger' WHERE `MobId` = 295;
UPDATE `Mobs` SET `MobDescription` = 'Giant tiger' WHERE `MobId` = 296;
UPDATE `Mobs` SET `MobDescription` = 'Golden tiger' WHERE `MobId` = 297;
UPDATE `Mobs` SET `MobDescription` = 'Mercenary' WHERE `MobId` = 305;
UPDATE `Mobs` SET `MobDescription` = 'Pine fox' WHERE `MobId` = 306;
UPDATE `Mobs` SET `MobDescription` = 'Pine wolf' WHERE `MobId` = 307;
UPDATE `Mobs` SET `MobDescription` = 'Pine raven' WHERE `MobId` = 308;
UPDATE `Mobs` SET `MobDescription` = 'Cow' WHERE `MobId` = 309;
UPDATE `Mobs` SET `MobDescription` = 'Strange thing' WHERE `MobId` = 313;
UPDATE `Mobs` SET `MobDescription` = 'Crow' WHERE `MobId` = 314;
UPDATE `Mobs` SET `MobDescription` = 'Mercenary' WHERE `MobId` = 317;
UPDATE `Mobs` SET `MobDescription` = 'Mercenary' WHERE `MobId` = 318;
UPDATE `Mobs` SET `MobDescription` = 'Mercenary' WHERE `MobId` = 319;
UPDATE `Mobs` SET `MobDescription` = 'Mercenary' WHERE `MobId` = 320;
UPDATE `Mobs` SET `MobDescription` = 'Mercenary' WHERE `MobId` = 321;
UPDATE `Mobs` SET `MobDescription` = 'Mercenary' WHERE `MobId` = 322;
UPDATE `Mobs` SET `MobDescription` = 'Mercenary' WHERE `MobId` = 323;
UPDATE `Mobs` SET `MobDescription` = 'Mercenary' WHERE `MobId` = 324;
UPDATE `Mobs` SET `MobDescription` = 'Mercenary' WHERE `MobId` = 325;
UPDATE `Mobs` SET `MobDescription` = 'Simple monkey' WHERE `MobId` = 326;
UPDATE `Mobs` SET `MobDescription` = 'Monkey guardian' WHERE `MobId` = 330;
UPDATE `Mobs` SET `MobDescription` = 'Divine monkey' WHERE `MobId` = 331;
UPDATE `Mobs` SET `MobDescription` = 'Spunky monkey' WHERE `MobId` = 335;
UPDATE `Mobs` SET `MobDescription` = 'Monkey defender' WHERE `MobId` = 337;
UPDATE `Mobs` SET `MobDescription` = 'Spirit monkey' WHERE `MobId` = 338;
UPDATE `Mobs` SET `MobDescription` = 'Monkey avenger' WHERE `MobId` = 339;
UPDATE `Mobs` SET `MobDescription` = 'Tiger warrior' WHERE `MobId` = 341;
UPDATE `Mobs` SET `MobDescription` = 'Raging tiger' WHERE `MobId` = 342;
UPDATE `Mobs` SET `MobDescription` = 'Black tiger' WHERE `MobId` = 343;
UPDATE `Mobs` SET `MobDescription` = 'Divine tiger' WHERE `MobId` = 345;
UPDATE `Mobs` SET `MobDescription` = 'Tiger slasher' WHERE `MobId` = 346;
UPDATE `Mobs` SET `MobDescription` = 'Spirit tiger' WHERE `MobId` = 350;
UPDATE `Mobs` SET `MobDescription` = 'Tiger avenger' WHERE `MobId` = 351;
UPDATE `Mobs` SET `MobDescription` = 'Stout piglet' WHERE `MobId` = 352;
UPDATE `Mobs` SET `MobDescription` = 'Stout pig' WHERE `MobId` = 353;
UPDATE `Mobs` SET `MobDescription` = 'Stout warthog' WHERE `MobId` = 355;
UPDATE `Mobs` SET `MobDescription` = 'Pig guardian' WHERE `MobId` = 356;
UPDATE `Mobs` SET `MobDescription` = 'Divine pig' WHERE `MobId` = 357;
UPDATE `Mobs` SET `MobDescription` = 'Pig champion' WHERE `MobId` = 358;
UPDATE `Mobs` SET `MobDescription` = 'Bold piglet' WHERE `MobId` = 359;
UPDATE `Mobs` SET `MobDescription` = 'Bold pig' WHERE `MobId` = 360;
UPDATE `Mobs` SET `MobDescription` = 'Bold boar' WHERE `MobId` = 362;
UPDATE `Mobs` SET `MobDescription` = 'Boar defender' WHERE `MobId` = 363;
UPDATE `Mobs` SET `MobDescription` = 'Spirit pig' WHERE `MobId` = 364;
UPDATE `Mobs` SET `MobDescription` = 'Pig avenger' WHERE `MobId` = 365;
UPDATE `Mobs` SET `MobDescription` = 'Giant bull' WHERE `MobId` = 366;
UPDATE `Mobs` SET `MobDescription` = 'Angry ox' WHERE `MobId` = 368;
UPDATE `Mobs` SET `MobDescription` = 'Ox guardian' WHERE `MobId` = 369;
UPDATE `Mobs` SET `MobDescription` = 'Divine ox' WHERE `MobId` = 370;
UPDATE `Mobs` SET `MobDescription` = 'Ox defender' WHERE `MobId` = 375;
UPDATE `Mobs` SET `MobDescription` = 'Spirit ox' WHERE `MobId` = 376;
UPDATE `Mobs` SET `MobDescription` = 'Ox avenger' WHERE `MobId` = 377;
UPDATE `Mobs` SET `MobDescription` = 'Horse swordsman' WHERE `MobId` = 379;
UPDATE `Mobs` SET `MobDescription` = 'Golden horse' WHERE `MobId` = 381;
UPDATE `Mobs` SET `MobDescription` = 'Horse guardian' WHERE `MobId` = 382;
UPDATE `Mobs` SET `MobDescription` = 'Divine horse' WHERE `MobId` = 383;
UPDATE `Mobs` SET `MobDescription` = 'Horse defender' WHERE `MobId` = 389;
UPDATE `Mobs` SET `MobDescription` = 'Spirit horse' WHERE `MobId` = 390;
UPDATE `Mobs` SET `MobDescription` = 'Horse avenger' WHERE `MobId` = 391;
UPDATE `Mobs` SET `MobDescription` = 'Black sheep' WHERE `MobId` = 392;
UPDATE `Mobs` SET `MobDescription` = 'Red sheep' WHERE `MobId` = 393;
UPDATE `Mobs` SET `MobDescription` = 'Sheep guardian' WHERE `MobId` = 394;
UPDATE `Mobs` SET `MobDescription` = 'Divine sheep' WHERE `MobId` = 395;
UPDATE `Mobs` SET `MobDescription` = 'Dark sheep' WHERE `MobId` = 398;
UPDATE `Mobs` SET `MobDescription` = 'Sheep defender' WHERE `MobId` = 399;
UPDATE `Mobs` SET `MobDescription` = 'Spirit sheep' WHERE `MobId` = 400;
UPDATE `Mobs` SET `MobDescription` = 'Sheep avenger' WHERE `MobId` = 401;
UPDATE `Mobs` SET `MobDescription` = 'Spunky dog' WHERE `MobId` = 404;
UPDATE `Mobs` SET `MobDescription` = 'Dog guardian' WHERE `MobId` = 406;
UPDATE `Mobs` SET `MobDescription` = 'Divine dog' WHERE `MobId` = 407;
UPDATE `Mobs` SET `MobDescription` = 'Killer mongrel' WHERE `MobId` = 411;
UPDATE `Mobs` SET `MobDescription` = 'Dog defender' WHERE `MobId` = 413;
UPDATE `Mobs` SET `MobDescription` = 'Spirit dog' WHERE `MobId` = 414;
UPDATE `Mobs` SET `MobDescription` = 'Dog avenger' WHERE `MobId` = 415;
UPDATE `Mobs` SET `MobDescription` = 'Dragon guardian' WHERE `MobId` = 420;
UPDATE `Mobs` SET `MobDescription` = 'Divine dragon' WHERE `MobId` = 421;
UPDATE `Mobs` SET `MobDescription` = 'Dragon slayer' WHERE `MobId` = 422;
UPDATE `Mobs` SET `MobDescription` = 'Great wyrm' WHERE `MobId` = 423;
UPDATE `Mobs` SET `MobDescription` = 'Mighty wyrm' WHERE `MobId` = 424;
UPDATE `Mobs` SET `MobDescription` = 'Old dragon' WHERE `MobId` = 425;
UPDATE `Mobs` SET `MobDescription` = 'Dragon defender' WHERE `MobId` = 426;
UPDATE `Mobs` SET `MobDescription` = 'Spirit dragon' WHERE `MobId` = 427;
UPDATE `Mobs` SET `MobDescription` = 'Dragon avenger' WHERE `MobId` = 428;
UPDATE `Mobs` SET `MobDescription` = 'Snake shaman' WHERE `MobId` = 430;
UPDATE `Mobs` SET `MobDescription` = 'Simple snake' WHERE `MobId` = 432;
UPDATE `Mobs` SET `MobDescription` = 'Lava snake' WHERE `MobId` = 433;
UPDATE `Mobs` SET `MobDescription` = 'Dark snake' WHERE `MobId` = 435;
UPDATE `Mobs` SET `MobDescription` = 'Snake guardian' WHERE `MobId` = 436;
UPDATE `Mobs` SET `MobDescription` = 'Divine snake' WHERE `MobId` = 437;
UPDATE `Mobs` SET `MobDescription` = 'Snake mage' WHERE `MobId` = 438;
UPDATE `Mobs` SET `MobDescription` = 'Storm snake' WHERE `MobId` = 442;
UPDATE `Mobs` SET `MobDescription` = 'Snake defender' WHERE `MobId` = 443;
UPDATE `Mobs` SET `MobDescription` = 'Spirit snake' WHERE `MobId` = 444;
UPDATE `Mobs` SET `MobDescription` = 'Snake avenger' WHERE `MobId` = 445;
UPDATE `Mobs` SET `MobDescription` = 'Rooster sentry' WHERE `MobId` = 446;
UPDATE `Mobs` SET `MobDescription` = 'Rooster swordsman' WHERE `MobId` = 448;
UPDATE `Mobs` SET `MobDescription` = 'Red chick' WHERE `MobId` = 449;
UPDATE `Mobs` SET `MobDescription` = 'White chicken' WHERE `MobId` = 451;
UPDATE `Mobs` SET `MobDescription` = 'White rooster' WHERE `MobId` = 452;
UPDATE `Mobs` SET `MobDescription` = 'Rooster guardian' WHERE `MobId` = 453;
UPDATE `Mobs` SET `MobDescription` = 'Divine rooster' WHERE `MobId` = 454;
UPDATE `Mobs` SET `MobDescription` = 'Wild chick' WHERE `MobId` = 456;
UPDATE `Mobs` SET `MobDescription` = 'Black chicken' WHERE `MobId` = 457;
UPDATE `Mobs` SET `MobDescription` = 'Rooster defender' WHERE `MobId` = 460;
UPDATE `Mobs` SET `MobDescription` = 'Spirit rooster' WHERE `MobId` = 461;
UPDATE `Mobs` SET `MobDescription` = 'Rooster avenger' WHERE `MobId` = 462;
UPDATE `Mobs` SET `MobDescription` = 'Stone ogre' WHERE `MobId` = 465;
UPDATE `Mobs` SET `MobDescription` = 'Shadow Mantis' WHERE `MobId` = 468;
UPDATE `Mobs` SET `MobDescription` = 'Dark Mantis' WHERE `MobId` = 469;
UPDATE `Mobs` SET `MobDescription` = 'Ghost Mantis' WHERE `MobId` = 471;
UPDATE `Mobs` SET `MobDescription` = 'Iron Tiger' WHERE `MobId` = 476;
UPDATE `Mobs` SET `MobDescription` = 'Giant Iron Tiger' WHERE `MobId` = 477;
UPDATE `Mobs` SET `MobDescription` = 'Black skeleton' WHERE `MobId` = 479;
UPDATE `Mobs` SET `MobDescription` = 'Snow beast' WHERE `MobId` = 489;
UPDATE `Mobs` SET `MobDescription` = 'Snow rabbit' WHERE `MobId` = 491;
UPDATE `Mobs` SET `MobDescription` = 'Slush ogre' WHERE `MobId` = 493;
UPDATE `Mobs` SET `MobDescription` = 'Snow ogre' WHERE `MobId` = 494;
UPDATE `Mobs` SET `MobDescription` = 'Sleet ogre' WHERE `MobId` = 495;
UPDATE `Mobs` SET `MobDescription` = 'Blizzard ogre' WHERE `MobId` = 498;
UPDATE `Mobs` SET `MobDescription` = 'Tempest ogre' WHERE `MobId` = 500;
UPDATE `Mobs` SET `MobDescription` = 'Slush king' WHERE `MobId` = 502;
UPDATE `Mobs` SET `MobDescription` = 'Snow king' WHERE `MobId` = 503;
UPDATE `Mobs` SET `MobDescription` = 'Sleet king' WHERE `MobId` = 504;
UPDATE `Mobs` SET `MobDescription` = 'Blizzard king' WHERE `MobId` = 507;
UPDATE `Mobs` SET `MobDescription` = 'Tempest king' WHERE `MobId` = 509;
UPDATE `Mobs` SET `MobDescription` = 'Bear' WHERE `MobId` = 511;
UPDATE `Mobs` SET `MobDescription` = 'Tiger' WHERE `MobId` = 512;
UPDATE `Mobs` SET `MobDescription` = 'Golden Lobster' WHERE `MobId` = 517;
UPDATE `Mobs` SET `MobDescription` = 'Golden hare' WHERE `MobId` = 518;
UPDATE `Mobs` SET `MobDescription` = 'Mad rabbit' WHERE `MobId` = 519;
UPDATE `Mobs` SET `MobDescription` = 'Giant hare' WHERE `MobId` = 520;
UPDATE `Mobs` SET `MobDescription` = 'Rabbit sentry' WHERE `MobId` = 521;
UPDATE `Mobs` SET `MobDescription` = 'Hare witch' WHERE `MobId` = 523;
UPDATE `Mobs` SET `MobDescription` = 'Mad hare' WHERE `MobId` = 524;
UPDATE `Mobs` SET `MobDescription` = 'Giant rabbit' WHERE `MobId` = 525;
UPDATE `Mobs` SET `MobDescription` = 'Rabbit guardian' WHERE `MobId` = 526;
UPDATE `Mobs` SET `MobDescription` = 'Divine rabbit' WHERE `MobId` = 527;
UPDATE `Mobs` SET `MobDescription` = 'Rabbit witch' WHERE `MobId` = 528;
UPDATE `Mobs` SET `MobDescription` = 'Rabbit defender' WHERE `MobId` = 532;
UPDATE `Mobs` SET `MobDescription` = 'Spirit rabbit' WHERE `MobId` = 533;
UPDATE `Mobs` SET `MobDescription` = 'Rabbit avenger' WHERE `MobId` = 534;
UPDATE `Mobs` SET `MobDescription` = 'Ore' WHERE `MobId` = 535;
UPDATE `Mobs` SET `MobDescription` = 'Silver ore vein' WHERE `MobId` = 540;
UPDATE `Mobs` SET `MobDescription` = 'Tall wheat' WHERE `MobId` = 543;
UPDATE `Mobs` SET `MobDescription` = 'Storm' WHERE `MobId` = 549;
UPDATE `Mobs` SET `MobDescription` = 'Blizzard' WHERE `MobId` = 550;
UPDATE `Mobs` SET `MobDescription` = 'Vile scorpion' WHERE `MobId` = 554;
UPDATE `Mobs` SET `MobDescription` = 'Radiant scorpion' WHERE `MobId` = 556;
UPDATE `Mobs` SET `MobDescription` = 'Wild monkey' WHERE `MobId` = 565;
UPDATE `Mobs` SET `MobDescription` = 'Wind warrior' WHERE `MobId` = 568;
UPDATE `Mobs` SET `MobDescription` = 'Young spirit' WHERE `MobId` = 569;
UPDATE `Mobs` SET `MobDescription` = 'Angry spirit' WHERE `MobId` = 571;
UPDATE `Mobs` SET `MobDescription` = 'Ancient spirit' WHERE `MobId` = 574;
UPDATE `Mobs` SET `MobDescription` = 'Spirit guardian' WHERE `MobId` = 575;
UPDATE `Mobs` SET `MobDescription` = 'Spirit defender' WHERE `MobId` = 576;
UPDATE `Mobs` SET `MobDescription` = 'Spirit champion' WHERE `MobId` = 577;
UPDATE `Mobs` SET `MobDescription` = 'Golden rabbit' WHERE `MobId` = 599;
UPDATE `Mobs` SET `MobDescription` = 'Dragon mage' WHERE `MobId` = 602;
UPDATE `Mobs` SET `MobDescription` = 'Divine dragon' WHERE `MobId` = 603;
UPDATE `Mobs` SET `MobDescription` = 'Dragon slayer' WHERE `MobId` = 604;
UPDATE `Mobs` SET `MobDescription` = 'Spirit dragon' WHERE `MobId` = 605;
UPDATE `Mobs` SET `MobDescription` = 'Dragon avenger' WHERE `MobId` = 606;
UPDATE `Mobs` SET `MobDescription` = 'Dog assassin' WHERE `MobId` = 608;
UPDATE `Mobs` SET `MobDescription` = 'Divine dog' WHERE `MobId` = 609;
UPDATE `Mobs` SET `MobDescription` = 'Spirit dog' WHERE `MobId` = 611;
UPDATE `Mobs` SET `MobDescription` = 'Dog avenger' WHERE `MobId` = 612;
UPDATE `Mobs` SET `MobDescription` = 'Divine horse' WHERE `MobId` = 615;
UPDATE `Mobs` SET `MobDescription` = 'Spirit horse' WHERE `MobId` = 617;
UPDATE `Mobs` SET `MobDescription` = 'Horse avenger' WHERE `MobId` = 618;
UPDATE `Mobs` SET `MobDescription` = 'Divine monkey' WHERE `MobId` = 621;
UPDATE `Mobs` SET `MobDescription` = 'Spirit monkey' WHERE `MobId` = 623;
UPDATE `Mobs` SET `MobDescription` = 'Monkey avenger' WHERE `MobId` = 624;
UPDATE `Mobs` SET `MobDescription` = 'Divine ox' WHERE `MobId` = 627;
UPDATE `Mobs` SET `MobDescription` = 'Spirit ox' WHERE `MobId` = 629;
UPDATE `Mobs` SET `MobDescription` = 'Ox avenger' WHERE `MobId` = 630;
UPDATE `Mobs` SET `MobDescription` = 'Boar champion' WHERE `MobId` = 632;
UPDATE `Mobs` SET `MobDescription` = 'Divine pig' WHERE `MobId` = 633;
UPDATE `Mobs` SET `MobDescription` = 'Pig champion' WHERE `MobId` = 634;
UPDATE `Mobs` SET `MobDescription` = 'Spirit pig' WHERE `MobId` = 635;
UPDATE `Mobs` SET `MobDescription` = 'Pig avenger' WHERE `MobId` = 636;
UPDATE `Mobs` SET `MobDescription` = 'Hare witch' WHERE `MobId` = 638;
UPDATE `Mobs` SET `MobDescription` = 'Divine rabbit' WHERE `MobId` = 639;
UPDATE `Mobs` SET `MobDescription` = 'Rabbit witch' WHERE `MobId` = 640;
UPDATE `Mobs` SET `MobDescription` = 'Spirit rabbit' WHERE `MobId` = 641;
UPDATE `Mobs` SET `MobDescription` = 'Rabbit avenger' WHERE `MobId` = 642;
UPDATE `Mobs` SET `MobDescription` = 'Mighty mouse' WHERE `MobId` = 644;
UPDATE `Mobs` SET `MobDescription` = 'Divine rat' WHERE `MobId` = 645;
UPDATE `Mobs` SET `MobDescription` = 'Spirit rat' WHERE `MobId` = 647;
UPDATE `Mobs` SET `MobDescription` = 'Rat avenger' WHERE `MobId` = 648;
UPDATE `Mobs` SET `MobDescription` = 'Rooster swordsman' WHERE `MobId` = 650;
UPDATE `Mobs` SET `MobDescription` = 'Divine rooster' WHERE `MobId` = 651;
UPDATE `Mobs` SET `MobDescription` = 'Spirit rooster' WHERE `MobId` = 653;
UPDATE `Mobs` SET `MobDescription` = 'Rooster avenger' WHERE `MobId` = 654;
UPDATE `Mobs` SET `MobDescription` = 'Divine sheep' WHERE `MobId` = 655;
UPDATE `Mobs` SET `MobDescription` = 'Sheep avenger' WHERE `MobId` = 657;
UPDATE `Mobs` SET `MobDescription` = 'Sheep veteran' WHERE `MobId` = 659;
UPDATE `Mobs` SET `MobDescription` = 'Spirit sheep' WHERE `MobId` = 660;
UPDATE `Mobs` SET `MobDescription` = 'Snake shaman' WHERE `MobId` = 662;
UPDATE `Mobs` SET `MobDescription` = 'Divine snake' WHERE `MobId` = 663;
UPDATE `Mobs` SET `MobDescription` = 'Snake mage' WHERE `MobId` = 664;
UPDATE `Mobs` SET `MobDescription` = 'Spirit snake' WHERE `MobId` = 665;
UPDATE `Mobs` SET `MobDescription` = 'Snake avenger' WHERE `MobId` = 666;
UPDATE `Mobs` SET `MobDescription` = 'Tiger warrior' WHERE `MobId` = 668;
UPDATE `Mobs` SET `MobDescription` = 'Divine tiger' WHERE `MobId` = 669;
UPDATE `Mobs` SET `MobDescription` = 'Tiger slasher' WHERE `MobId` = 670;
UPDATE `Mobs` SET `MobDescription` = 'Spirit tiger' WHERE `MobId` = 671;
UPDATE `Mobs` SET `MobDescription` = 'Tiger avenger' WHERE `MobId` = 672;
UPDATE `Mobs` SET `MobDescription` = 'Fox' WHERE `MobId` = 673;
UPDATE `Mobs` SET `MobDescription` = 'Sheep' WHERE `MobId` = 674;
UPDATE `Mobs` SET `MobDescription` = 'Dark fox' WHERE `MobId` = 675;
UPDATE `Mobs` SET `MobDescription` = 'Blood fox' WHERE `MobId` = 676;
UPDATE `Mobs` SET `MobDescription` = 'Lava fox' WHERE `MobId` = 677;
UPDATE `Mobs` SET `MobDescription` = 'Sun fox' WHERE `MobId` = 678;
UPDATE `Mobs` SET `MobDescription` = 'Bear' WHERE `MobId` = 679;
UPDATE `Mobs` SET `MobDescription` = 'Rat' WHERE `MobId` = 680;
UPDATE `Mobs` SET `MobDescription` = 'Deer' WHERE `MobId` = 681;
UPDATE `Mobs` SET `MobDescription` = 'Rabbit' WHERE `MobId` = 682;
UPDATE `Mobs` SET `MobDescription` = 'Squirrel' WHERE `MobId` = 683;
UPDATE `Mobs` SET `MobDescription` = 'Sheep' WHERE `MobId` = 684;
UPDATE `Mobs` SET `MobDescription` = 'Snake' WHERE `MobId` = 685;
UPDATE `Mobs` SET `MobDescription` = 'Tiger' WHERE `MobId` = 686;
UPDATE `Mobs` SET `MobDescription` = 'Blood mouse' WHERE `MobId` = 687;
UPDATE `Mobs` SET `MobDescription` = 'Blood rat' WHERE `MobId` = 688;
UPDATE `Mobs` SET `MobDescription` = 'Snake' WHERE `MobId` = 689;
UPDATE `Mobs` SET `MobDescription` = 'Nine-tailed fox' WHERE `MobId` = 693;
UPDATE `Mobs` SET `MobDescription` = 'Red wolf' WHERE `MobId` = 708;
UPDATE `Mobs` SET `MobDescription` = 'Green squirrel' WHERE `MobId` = 709;
UPDATE `Mobs` SET `MobDescription` = 'Black lobster' WHERE `MobId` = 710;
UPDATE `Mobs` SET `MobDescription` = 'Rabbit' WHERE `MobId` = 711;
UPDATE `Mobs` SET `MobDescription` = 'Fox' WHERE `MobId` = 712;
UPDATE `Mobs` SET `MobDescription` = 'Bear' WHERE `MobId` = 713;
UPDATE `Mobs` SET `MobDescription` = 'Tiger' WHERE `MobId` = 714;
UPDATE `Mobs` SET `MobDescription` = 'Abyssal Hare' WHERE `MobId` = 733;
UPDATE `Mobs` SET `MobDescription` = 'Abyssal Rabbit' WHERE `MobId` = 734;
UPDATE `Mobs` SET `MobDescription` = 'abyssal monkey1' WHERE `MobId` = 738;
UPDATE `Mobs` SET `MobDescription` = 'abyssal dog1' WHERE `MobId` = 744;
UPDATE `Mobs` SET `MobDescription` = 'Abyssal Chick' WHERE `MobId` = 751;
UPDATE `Mobs` SET `MobDescription` = 'Abyssal Chicken' WHERE `MobId` = 752;
UPDATE `Mobs` SET `MobDescription` = 'abyssal rat1' WHERE `MobId` = 756;
UPDATE `Mobs` SET `MobDescription` = 'abyssal horse1' WHERE `MobId` = 762;
UPDATE `Mobs` SET `MobDescription` = 'abyssal ox1' WHERE `MobId` = 768;
UPDATE `Mobs` SET `MobDescription` = 'abyssal pig1' WHERE `MobId` = 774;
UPDATE `Mobs` SET `MobDescription` = 'abyssal sheep1' WHERE `MobId` = 786;
UPDATE `Mobs` SET `MobDescription` = 'Abyssal Wyrm' WHERE `MobId` = 800;
UPDATE `Mobs` SET `MobDescription` = 'Tiger sentry' WHERE `MobId` = 900;
UPDATE `Mobs` SET `MobDescription` = 'Tiger guardian' WHERE `MobId` = 901;
UPDATE `Mobs` SET `MobDescription` = 'Tiger defender' WHERE `MobId` = 902;
